### PR TITLE
fix generate job description

### PR DESCRIPTION
**Pull request by maulanamaleek**
| Status | ✅ Ready |
| -- | -- |

Ticket: https://app.clickup.com/t/86epbfca5

fix:
- get content when first open the accordion
- add separate loading skeleton for each loading

| Examples | 
| -- |
|Examples Demo|

### CODE REVIEW

**Comment by maulanamaleek** [comment]
@dwicaksono please help to review this 🙏

**Comment by dwicaksono** [comment]
Ini sama issue create job yg error atau nanti terpisah PR nya ?

**Comment by maulanamaleek** [comment]
> Ini sama issue create job yg error atau nanti terpisah PR nya ?

terpisah @dwicaksono , karena issue create job lebih kompleks untuk didebug

**Comment by dwicaksono** [comment]
Ok gue merged dlu kalau gtu yg ini

**Pull request merged**
